name: Tests 'setup1-contributor'
on:
  pull_request:
  push:
    branches:
      - master
env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    strategy:
      matrix:
        rust:
          - stable
    #          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Move into setup1-contributor
        run: cd setup1-contributor

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --examples --all --benches --no-fail-fast

  test-azure:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    #          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Move into setup1-contributor
        run: cd setup1-contributor

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features azure --examples --all --benches --no-fail-fast
